### ISSUE TITLE
Columns structure change to named tuples breaks a lot of agg/vecagg functionality

### ISSUE THREAD

**Issue by pazzo83** [JuliaComputing/IndexedTables.jl#74]
Hi, I utilize IndexedTables in my NOAAData package, and I had been utilizing the convertdim feature to do aggregations on various data.  However, the recent changes to the IndexedTable structure seem to have broken a lot of this.  I can explain below.

Let's say I have a table that looks like this:
```julia
DATE       │ TMAX
───────────┼─────
2015-01-01 │ 3.9
2015-01-02 │ 5.6
2015-01-03 │ 5.6
2015-01-04 │ 13.3
2015-01-05 │ 9.4
2015-01-06 │ -5.5
2015-01-07 │ -4.9
2015-01-08 │ -6.0
2015-01-09 │ 0.6
2015-01-10 │ -4.9
           ⋮
2015-12-22 │ 16.7
2015-12-23 │ 17.8
2015-12-24 │ 22.2
2015-12-25 │ 18.9
2015-12-26 │ 15.0
2015-12-27 │ 16.1
2015-12-28 │ 7.8
2015-12-29 │ 7.8
2015-12-30 │ 8.9
2015-12-31 │ 8.9
```
If I wanted to do a mean over each month, this used to work:
```julia
convertdim(myTable, 1, Dates.month, vecagg=mean)
```
However, now I am getting this method error:
```julia
ERROR: MethodError: no method matching +(::NamedTuples._NT_TMAX{Float64}, ::NamedTuples._NT_TMAX{Float64})
```
Because these are now named tuples, it can't add things together (as would be needed in the mean function).
Is there any way to do this now, or is this permanently impossible?

Thanks!

**Comment by shashi** [comment]
I find it surprising that

```
convertdim(myTable, 1, Dates.month, vecagg=mean)
```
used to work before... I think what ended up happening was, in a previous step before the convertdim some operation got smarter at keeping the names of the output columns and you ended up with a vector of named tuples instead of a vector of floats...

You can have the data not be named tuples, by using `map(pick(:TMAX), myTable)` instead of myTable. In this case data will be a single vector of floats rather than a vector of named tuples with one float in them.

Sorry for this inconvenience! :sweat_smile:
